name: AzureARM-CICD
on:
  push:
    branches: [arm-keyvault]

jobs:
  build_api_app:
      name: 🧪 Build API App
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
          
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./Tailspin.SpaceGame.LeaderboardContainer
        
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./Tailspin.SpaceGame.LeaderboardContainer
             
      - name: Publish
        run: dotnet publish --no-restore -c Release
        working-directory: ./Tailspin.SpaceGame.LeaderboardContainer
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: spacegameleaderboard
          path: ./Tailspin.SpaceGame.LeaderboardContainer/bin/Release/netcoreapp3.1/publish/

  build_web_app:
      name: 🧪 Build Web App
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
        
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./Tailspin.SpaceGame.Web
        
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./Tailspin.SpaceGame.Web
      
      - name: Publish
        run: dotnet publish --no-restore -c Release
        working-directory: ./Tailspin.SpaceGame.Web
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: spacegameweb
          path: ./Tailspin.SpaceGame.Web/bin/Release/netcoreapp3.1/publish/

  deploy:
    runs-on: ubuntu-latest
    environment: ARM-KEYVAULT
    steps:
    - uses: actions/checkout@v2
    
    - name: Download spacegameleaderboard
      uses: actions/download-artifact@v2.0.7
      with:
        name: spacegameleaderboard
        path: leaderboard
        
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_ARM_CREDS }}
        
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: tailspin-arm
        template: Deployments/arm-templates/azuredeploy.json        
      id: arm_deploy
      
    - name: Api Deploy
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{steps.arm_deploy.outputs.apiappname}}
        package: leaderboard
    
  #  - name: Web Deploy
  #    uses: Azure/webapps-deploy@v2
  #    with:
  #      app-name: ${{steps.arm_deploy.outputs.apiappname}}
