name: Tailspin-Web.k8s

on:
  push: 
    branches: 
      - trunk
    paths:
      - .github/workflows/tailspinweb-aks.yml
      - Tailspin.SpaceGame.Web/**
      - manifests/webdeployments.yml
  workflow_dispatch:
  
jobs:
  dockerpush:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
          
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
      
      - name: Configure App Settings
        uses: cschleiden/replace-tokens@v1
        with: 
         files: '["Tailspin.SpaceGame.Web/appsettings.json"]'
        env:
         LEADERBOARD_API_URL: "Test"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Tailspin.SpaceGame.Web/Dockerfile
          push: true
          tags: |
            ghcr.io/WorkshopOrgTest/spacegameweb:latest
            ghcr.io/WorkshopOrgTest/spacegameweb:${{ steps.date.outputs.date }}.${{ github.run_number }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  
  anchore:
    name: Anchore Analyse
    needs: dockerpush
    runs-on: ubuntu-latest
    steps:  
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
          
      - name: Anchor Scan Web image
        uses: anchore/scan-action@main
        with:
          image: "ghcr.io/WorkshopOrgTest/spacegameweb:latest"
          acs-report-enable: true
          fail-build: true
          severity-cutoff: critical
        continue-on-error: true
         
      - name: Upload Anchore Scan Report
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
          
  AKS_deploy:
    name: Deploy to AKS
    environment: 
      name: AKS Cluster
    runs-on: ubuntu-latest
    needs: anchore
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2   
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
    
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}
  
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}
        resource-group: canarysdemo
        cluster-name: democluster
    
    - uses: azure/k8s-create-secret@v1
      name: Create imagepullsecret for GCR
      with:
        container-registry-url: ghcr.io
        container-registry-username: ${{ github.repository_owner }}
        container-registry-password: ${{ secrets.PAT }}
        secret-name: aks-connection
        
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v1
      with:       
        manifests: manifests/webdeployments.yml      
        images: ghcr.io/WorkshopOrgTest/spacegameweb:${{ steps.date.outputs.date }}.${{ github.run_number }}
        imagepullsecrets: |
          aks-connection
        force: true
   
    
