name: Tailspin Leaderboard Kubernetes (Disabled)

on:
  push:
    branches-ignore: 
      - '**'
    paths:
      - .github/workflows/tailspinleaderboard-cicd.yml
      - Tailspin.SpaceGame.LeaderboardContainer/**
      - manifests/apideployments.yml
  workflow_dispatch:
  
jobs:
  dockerpush:
    name: DOCKER BUILD & PUSH
    runs-on: ubuntu-latest    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Tailspin.SpaceGame.LeaderboardContainer/Dockerfile
          push: true
          tags: |
            ghcr.io/canarysplayground/spacegameleaderboard:latest
            ghcr.io/canarysplayground/spacegameleaderboard:${{ steps.date.outputs.date }}.${{ github.run_number }}
       
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
  
  # --------------------------------------------------------------------------------------------------------------
  # build:
  #   name: DOTNET BUILD
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
      
  #   - name: Setup .NET
  #     uses: actions/setup-dotnet@v1
  #     with:
  #       dotnet-version: 3.1.301
        
  #   - name: Restore dependencies
  #     run: dotnet restore
  #     working-directory: ./Tailspin.SpaceGame.LeaderboardContainer
      
  #   - name: Build
  #     run: dotnet build --no-restore
  #     working-directory: ./Tailspin.SpaceGame.LeaderboardContainer
      
  #   - name: Test
  #     run: dotnet test --no-build --verbosity normal
  #     working-directory: ./Tailspin.SpaceGame.LeaderboardContainer
    
  #   - name: Publish
  #     run: dotnet publish --no-restore -c Release
  #     working-directory: ./Tailspin.SpaceGame.LeaderboardContainer
    
  #   - name: Upload a Build Artifact
  #     uses: actions/upload-artifact@v2.2.1
  #     with:
  #       name: drop
  #       path: ./Tailspin.SpaceGame.LeaderboardContainer/bin/Release/netcoreapp3.1/publish/
  
  # appservicedeploy:
  #   name: AZURE APP SERVICE DEPLOY
  #   if: ${{ github.event.inputs.aks_deploy }} == true
  #   runs-on: ubuntu-latest
  #   environment: 
  #     name: API App
  #     url: https://leaderboardsgh.azurewebsites.net/api/Leaderboard
  #   needs:
  #   - build
  #   - dockerpush
  #   steps:
      
  #   - name: Download a Build Artifact
  #     uses: actions/download-artifact@v2.0.7
  #     with:
  #       name: drop
        
  #   - name: Azure Login
  #     uses: Azure/login@v1.1
  #     with:
  #       creds: ${{ secrets.AZURE_CREDS }}
        
  #   - name: Azure WebApp
  #     uses: Azure/webapps-deploy@v2
  #     with:
  #       app-name: leaderboardsgh
  #       package: .
